// apps/server/web/src/components/admin/UserManagement.tsx
import { useState, useEffect } from "react"
import { useTranslation } from "react-i18next"
import { Plus, Pencil, Trash2, Key, Users, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useAuth } from "@/contexts/AuthContext"

interface User {
  id: number
  username: string
  email: string
  isSuperAdmin: boolean
  createdAt: string
  groups?: { id: number; name: string }[]
}

interface Group {
  id: number
  name: string
  description?: string
}

export function UserManagement() {
  const { t } = useTranslation()
  const { token } = useAuth()
  const [users, setUsers] = useState<User[]>([])
  const [groups, setGroups] = useState<Group[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  // Modal states
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [editingUser, setEditingUser] = useState<User | null>(null)
  const [changingPassword, setChangingPassword] = useState<User | null>(null)
  
  // Form states
  const [formData, setFormData] = useState({
    username: "",
    password: "",
    email: "",
    groupIds: [] as number[]
  })
  const [newPassword, setNewPassword] = useState("")

  useEffect(() => {
    fetchUsers()
    fetchGroups()
  }, [])

  const fetchUsers = async () => {
    try {
      const res = await fetch("/api/users", {
        headers: { Authorization: `Bearer ${token}` }
      })
      if (!res.ok) throw new Error("Failed to fetch users")
      const data = await res.json()
      setUsers(data)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error")
    } finally {
      setLoading(false)
    }
  }

  const fetchGroups = async () => {
    try {
      const res = await fetch("/api/groups", {
        headers: { Authorization: `Bearer ${token}` }
      })
      if (res.ok) {
        const data = await res.json()
        setGroups(data)
      }
    } catch {
      // Groups are optional
    }
  }

  const handleCreate = async () => {
    try {
      const res = await fetch("/api/users", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(formData)
      })
      if (!res.ok) {
        const err = await res.json()
        throw new Error(err.error || "Failed to create user")
      }
      setShowCreateModal(false)
      setFormData({ username: "", password: "", email: "", groupIds: [] })
      fetchUsers()
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error")
    }
  }

  const handleUpdate = async () => {
    if (!editingUser) return
    try {
      const res = await fetch(`/api/users/${editingUser.id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          email: formData.email,
          groupIds: formData.groupIds
        })
      })
      if (!res.ok) throw new Error("Failed to update user")
      setEditingUser(null)
      fetchUsers()
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error")
    }
  }

  const handleDelete = async (user: User) => {
    if (!confirm(`Delete user "${user.username}"?`)) return
    try {
      const res = await fetch(`/api/users/${user.id}`, {
        method: "DELETE",
        headers: { Authorization: `Bearer ${token}` }
      })
      if (!res.ok) throw new Error("Failed to delete user")
      fetchUsers()
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error")
    }
  }

  const handleChangePassword = async () => {
    if (!changingPassword) return
    try {
      const res = await fetch(`/api/users/${changingPassword.id}/password`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ newPassword, forceChange: true })
      })
      if (!res.ok) throw new Error("Failed to change password")
      setChangingPassword(null)
      setNewPassword("")
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error")
    }
  }

  const openEditModal = (user: User) => {
    setEditingUser(user)
    setFormData({
      username: user.username,
      password: "",
      email: user.email || "",
      groupIds: user.groups?.map(g => g.id) || []
    })
  }

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center p-12">
          <Loader2 className="h-8 w-8 animate-spin" />
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          <Users className="h-5 w-5" />
          {t("admin.userManagement")}
        </CardTitle>
        <Button onClick={() => setShowCreateModal(true)} size="sm">
          <Plus className="h-4 w-4 mr-1" />
          {t("admin.createUser")}
        </Button>
      </CardHeader>
      <CardContent>
        {error && (
          <div className="mb-4 p-3 bg-red-500/10 border border-red-500/50 rounded text-red-500">
            {error}
          </div>
        )}
        
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-[var(--color-border)]">
                <th className="text-left p-2">Username</th>
                <th className="text-left p-2">Email</th>
                <th className="text-left p-2">Role</th>
                <th className="text-left p-2">Groups</th>
                <th className="text-left p-2">Created</th>
                <th className="text-right p-2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {users.map(user => (
                <tr key={user.id} className="border-b border-[var(--color-border)] hover:bg-[var(--color-muted)]">
                  <td className="p-2 font-medium">{user.username}</td>
                  <td className="p-2 text-[var(--color-muted-foreground)]">{user.email || "-"}</td>
                  <td className="p-2">
                    {user.isSuperAdmin ? (
                      <span className="px-2 py-0.5 bg-yellow-500/20 text-yellow-500 rounded text-xs">
                        SuperAdmin
                      </span>
                    ) : (
                      <span className="px-2 py-0.5 bg-blue-500/20 text-blue-500 rounded text-xs">
                        User
                      </span>
                    )}
                  </td>
                  <td className="p-2">
                    {user.groups?.map(g => (
                      <span key={g.id} className="mr-1 px-2 py-0.5 bg-gray-500/20 rounded text-xs">
                        {g.name}
                      </span>
                    )) || "-"}
                  </td>
                  <td className="p-2 text-[var(--color-muted-foreground)]">
                    {new Date(user.createdAt).toLocaleDateString()}
                  </td>
                  <td className="p-2 text-right">
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="sm" onClick={() => openEditModal(user)}>
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => setChangingPassword(user)}>
                        <Key className="h-4 w-4" />
                      </Button>
                      {!user.isSuperAdmin && (
                        <Button variant="ghost" size="sm" onClick={() => handleDelete(user)}>
                          <Trash2 className="h-4 w-4 text-red-500" />
                        </Button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>

      {/* Create User Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-[var(--color-card)] rounded-lg p-6 w-full max-w-md mx-4">
            <h3 className="text-lg font-semibold mb-4">{t("admin.createUser")}</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Username</label>
                <input
                  type="text"
                  value={formData.username}
                  onChange={e => setFormData(p => ({ ...p, username: e.target.value }))}
                  className="w-full px-3 py-2 border border-[var(--color-border)] rounded bg-[var(--color-background)]"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Password</label>
                <input
                  type="password"
                  value={formData.password}
                  onChange={e => setFormData(p => ({ ...p, password: e.target.value }))}
                  className="w-full px-3 py-2 border border-[var(--color-border)] rounded bg-[var(--color-background)]"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Email (optional)</label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={e => setFormData(p => ({ ...p, email: e.target.value }))}
                  className="w-full px-3 py-2 border border-[var(--color-border)] rounded bg-[var(--color-background)]"
                />
              </div>
              {groups.length > 0 && (
                <div>
                  <label className="block text-sm font-medium mb-1">Groups</label>
                  <div className="flex flex-wrap gap-2">
                    {groups.map(g => (
                      <label key={g.id} className="flex items-center gap-1 text-sm">
                        <input
                          type="checkbox"
                          checked={formData.groupIds.includes(g.id)}
                          onChange={e => {
                            if (e.target.checked) {
                              setFormData(p => ({ ...p, groupIds: [...p.groupIds, g.id] }))
                            } else {
                              setFormData(p => ({ ...p, groupIds: p.groupIds.filter(id => id !== g.id) }))
                            }
                          }}
                        />
                        {g.name}
                      </label>
                    ))}
                  </div>
                </div>
              )}
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <Button variant="outline" onClick={() => setShowCreateModal(false)}>Cancel</Button>
              <Button onClick={handleCreate}>Create</Button>
            </div>
          </div>
        </div>
      )}

      {/* Edit User Modal */}
      {editingUser && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-[var(--color-card)] rounded-lg p-6 w-full max-w-md mx-4">
            <h3 className="text-lg font-semibold mb-4">Edit User: {editingUser.username}</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Email</label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={e => setFormData(p => ({ ...p, email: e.target.value }))}
                  className="w-full px-3 py-2 border border-[var(--color-border)] rounded bg-[var(--color-background)]"
                />
              </div>
              {groups.length > 0 && (
                <div>
                  <label className="block text-sm font-medium mb-1">Groups</label>
                  <div className="flex flex-wrap gap-2">
                    {groups.map(g => (
                      <label key={g.id} className="flex items-center gap-1 text-sm">
                        <input
                          type="checkbox"
                          checked={formData.groupIds.includes(g.id)}
                          onChange={e => {
                            if (e.target.checked) {
                              setFormData(p => ({ ...p, groupIds: [...p.groupIds, g.id] }))
                            } else {
                              setFormData(p => ({ ...p, groupIds: p.groupIds.filter(id => id !== g.id) }))
                            }
                          }}
                        />
                        {g.name}
                      </label>
                    ))}
                  </div>
                </div>
              )}
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <Button variant="outline" onClick={() => setEditingUser(null)}>Cancel</Button>
              <Button onClick={handleUpdate}>Save</Button>
            </div>
          </div>
        </div>
      )}

      {/* Change Password Modal */}
      {changingPassword && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-[var(--color-card)] rounded-lg p-6 w-full max-w-md mx-4">
            <h3 className="text-lg font-semibold mb-4">Change Password: {changingPassword.username}</h3>
            <div>
              <label className="block text-sm font-medium mb-1">New Password</label>
              <input
                type="password"
                value={newPassword}
                onChange={e => setNewPassword(e.target.value)}
                className="w-full px-3 py-2 border border-[var(--color-border)] rounded bg-[var(--color-background)]"
              />
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <Button variant="outline" onClick={() => setChangingPassword(null)}>Cancel</Button>
              <Button onClick={handleChangePassword}>Change Password</Button>
            </div>
          </div>
        </div>
      )}
    </Card>
  )
}

// apps/server/web/src/components/UserManagement.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useAuth } from '../composables/useAuth.js'

const emit = defineEmits(['back'])
const { authFetch } = useAuth()

const users = ref([])
const loading = ref(true)
const error = ref(null)
const showDeleteConfirm = ref(false)
const userToDelete = ref(null)

async function fetchUsers() {
  loading.value = true
  try {
    const res = await authFetch('/users')
    if (!res.ok) throw new Error('Failed to fetch users')
    users.value = await res.json()
    error.value = null
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

async function deleteUser(user) {
  try {
    const res = await authFetch(`/users/${user.id}`, { method: 'DELETE' })
    if (!res.ok) {
      const data = await res.json()
      throw new Error(data.error || 'Failed to delete user')
    }
    users.value = users.value.filter(u => u.id !== user.id)
    showDeleteConfirm.value = false
    userToDelete.value = null
  } catch (e) {
    error.value = e.message
  }
}

function confirmDelete(user) {
  userToDelete.value = user
  showDeleteConfirm.value = true
}

onMounted(fetchUsers)
</script>

<template>
  <div>
    <!-- Header -->
    <div class="flex items-center justify-between mb-6">
      <div>
        <h2 class="text-xl font-semibold">User Management</h2>
        <p class="text-sm text-gray-400 mt-1">Manage system users and their access</p>
      </div>
      <button @click="$emit('back')" class="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg flex items-center">
        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
        Back
      </button>
    </div>

    <!-- Error Alert -->
    <div v-if="error" class="mb-4 bg-red-900/50 border border-red-700 rounded-lg p-3">
      <p class="text-red-300 text-sm">{{ error }}</p>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="flex items-center justify-center py-12">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
    </div>

    <!-- Users Table -->
    <div v-else class="bg-gray-800 rounded-lg overflow-hidden">
      <table class="w-full">
        <thead class="bg-gray-700">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">User</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Email</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Role</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Created</th>
            <th class="px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase tracking-wider">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-700">
          <tr v-for="user in users" :key="user.id" class="hover:bg-gray-750">
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="flex items-center">
                <div class="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center mr-3">
                  <span class="text-sm font-medium text-white">{{ user.username?.charAt(0)?.toUpperCase() }}</span>
                </div>
                <span class="text-sm font-medium text-white">{{ user.username }}</span>
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
              {{ user.email || '-' }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span
                :class="user.isSuperAdmin ? 'bg-purple-600 text-purple-100' : 'bg-gray-600 text-gray-100'"
                class="px-2 py-1 text-xs font-medium rounded"
              >
                {{ user.isSuperAdmin ? 'Super Admin' : 'User' }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-400">
              {{ new Date(user.createdAt).toLocaleDateString() }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-right">
              <button
                v-if="!user.isSuperAdmin"
                @click="confirmDelete(user)"
                class="text-red-400 hover:text-red-300 text-sm"
              >
                Delete
              </button>
              <span v-else class="text-gray-500 text-sm">-</span>
            </td>
          </tr>
          <tr v-if="users.length === 0">
            <td colspan="5" class="px-6 py-8 text-center text-gray-400">
              No users found
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Delete Confirmation Modal -->
    <div v-if="showDeleteConfirm" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div class="bg-gray-800 rounded-lg p-6 max-w-md w-full mx-4 border border-gray-700">
        <h3 class="text-lg font-semibold text-white mb-2">Delete User</h3>
        <p class="text-gray-400 mb-6">
          Are you sure you want to delete <strong class="text-white">{{ userToDelete?.username }}</strong>? 
          This action cannot be undone.
        </p>
        <div class="flex justify-end space-x-3">
          <button
            @click="showDeleteConfirm = false"
            class="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg"
          >
            Cancel
          </button>
          <button
            @click="deleteUser(userToDelete)"
            class="px-4 py-2 bg-red-600 hover:bg-red-700 rounded-lg"
          >
            Delete
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
